### PR TITLE
Added prettier support

### PR DESCRIPTION
**Pull request by jamrizzi**

### CODE REVIEW

**Comment by jamrizzi** [comment]
This fixes issue #16

**Comment by ewnd9** [comment]
There is also an eslint plugin https://github.com/prettier/eslint-plugin-prettier although the project only contains cpp linting now

**Comment by Place1** [comment]
i'd be keen to add eslint with the plugin to be honest.

**Comment by jamrizzi** [comment]
I’ll add eslint, but that doesn’t replace prettier. Many JavaScript developers are using it now, and without prettierrc single quotes will get replaced by double quotes.

**Comment by Place1** [comment]
Yeah I just meant add eslint with the prettier plugin. The plugin uses your
eslint config to auto fix linter errors. If you eslint config specifies a
specific quote style (I.e single quotes) then when you run “eslint --fix”
it will use prettier to fix the code.

**Comment by jamrizzi** [comment]
I created a new issue for eslint. I’ll add it tomorrow. #23

**Pull request closed without merging**
