### PR TITLE
Examples builder

### PR DESCRIPTION
**Pull request by cedlemo**
a little example.

### CODE REVIEW

**Comment by ewnd9** [comment]
Please run `$ npm run lint` for formatting

**Comment by cedlemo** [comment]
@ewnd9 ,

done

**Comment by Place1** [comment]
Want me to merge?

**Comment by ewnd9** [comment]
I think every pull request is intended to be merged if not stated otherwise (e.g. failed state reproduction or work in progress).

By the way I've published a lot of automatically converted examples via codemod https://github.com/ewnd9/playground-gtk-javascript/tree/master/examples/universal-gtk-examples for my simple wrapper which combines `node-gir` with `cgjs` https://github.com/ewnd9/playground-gtk-javascript/blob/master/src/universal-gtk/index.js (it's a work in progress, I am going to add automatic report of failed ones when have time)

**Pull request merged**
